### ISSUE TITLE
Docs not super clear

### ISSUE THREAD

**Issue by Izhaki** [tngan/ts-express-angular2-node-boilerplate#2]
README says:

```
$ npm install ts-express-angular2-node-boilerplate
```

What does it do? installs it under `node_moudles`? You can't run `npm install` after it if you ran the previous command in an empty folder.

Shouldn't the instructions read:

```
$ git clone https://github.com/tngan/ts-express-angular2-node-boilerplate.git
$ cd ts-express-angular2-node-boilerplate
$ npm install
$ npm run tsc
$ npm start
```

**Comment by tngan** [comment]
@Izhaki You're right, let me update the README.md.

**Comment by Izhaki** [comment]
I still think that `npm run tsc` should be above `npm start` in the README... although it's kind of obvious you need to build from it'll run, other may (just like me) just follow the sequential order. 

Consider `npm run build` instead?

**Comment by tngan** [comment]
@Izhaki Feel free to make a pull request.
